cr_tests/userns_deep: fix -Wall warnings
userns/userns_deep.c: In function 'write_status':
userns/userns_deep.c:25: warning: implicit declaration of function 'getpid'
userns/userns_deep.c:25: warning: implicit declaration of function 'getuid'
userns/userns_deep.c: In function 'do_child':
userns/userns_deep.c:49: warning: implicit declaration of function 'do_clone'
userns/userns_deep.c:50: warning: implicit declaration of function 'setgid'
userns/userns_deep.c:51: warning: implicit declaration of function 'setuid'
userns/userns_deep.c:45: warning: unused variable 'ret'
userns/userns_deep.c: In function 'do_clone':
userns/userns_deep.c:63: warning: implicit declaration of function 'getpagesize'
userns/userns_deep.c: In function 'main':
userns/userns_deep.c:95: warning: implicit declaration of function 'close'

Include unistd.h; add forward declaration of do_clone (impossible to
avoid due to mutual recursion with do_child); remove unused variable.

Signed-off-by: Nathan Lynch <ntl@pobox.com>