cr_tests/libcrtest: fix -Wall warnings etc
common.c: In function 'test_done':
common.c:33: warning: control reaches end of non-void function
common.c: In function 'test_checkpoint_done':
common.c:47: warning: control reaches end of non-void function
common.c: In function 'set_checkpoint_ready':
common.c:53: warning: implicit declaration of function 'creat'
common.c: In function 'copy_data':
common.c:164: warning: unused variable 'fd'
common.c: In function 'create_cgroup':
common.c:306: warning: implicit declaration of function 'mkdir'

Add /* not reached */ return statements where appropriate.

Use int foo(void), not int foo().

Add proper #includes for mkdir and creat -- and fix wrong number of
arguments to the latter.

Remove unused variable from copy_data().

Signed-off-by: Nathan Lynch <ntl@pobox.com>