cr_tests/nsexec: fix -Wall warnings
ns_exec.c: In function ‘move_to_new_cgroup’:
ns_exec.c:150: warning: implicit declaration of function ‘mkdir’
ns_exec.c: In function ‘do_child’:
ns_exec.c:191: warning: unused variable ‘buf’
ns_exec.c:190: warning: unused variable ‘newgroup’
ns_exec.c:190: warning: unused variable ‘ret’
ns_exec.c: In function ‘write_pid’:
ns_exec.c:204: warning: unused variable ‘buf’
ns_exec.c: At top level:
ns_exec.c:49: warning: ‘print_my_info’ defined but not used

Include <sys/stat.h> for mkdir(2).

Remove unused local variables from various functions; #if 0
print_my_info.

Signed-off-by: Nathan Lynch <ntl@pobox.com>