cr_tests/usertask: fix -Wall warnings
userns/usertask.c: In function 'main':
userns/usertask.c:95: warning: implicit declaration of function 'setgroups'
userns/usertask.c:59: warning: unused variable 'fd'
userns/usertask.c:57: warning: unused variable 'ret'
userns/usertask.c:53: warning: unused variable 'pid'

Include grp.h for setgroups; remove unused variables.

Signed-off-by: Nathan Lynch <ntl@pobox.com>