cr_tests/chrootsleep: fix -Wall warnings
taskfs/chrootsleep.c: In function 'child':
taskfs/chrootsleep.c:26: warning: control reaches end of non-void function
taskfs/chrootsleep.c: In function 'main':
taskfs/chrootsleep.c:53: warning: implicit declaration of function 'waitpid'
taskfs/chrootsleep.c:32: warning: unused variable 'stack'

Add return statement to child(); include <sys/wait.h> for waitpid();
remove unused variable.

Signed-off-by: Nathan Lynch <ntl@pobox.com>