cr_tests/simple_deep: fix -Wall warnings
userns/simple_deep.c: In function 'write_status':
userns/simple_deep.c:25: warning: implicit declaration of function 'getpid'
userns/simple_deep.c:25: warning: implicit declaration of function 'getuid'
userns/simple_deep.c: In function 'do_child':
userns/simple_deep.c:49: warning: implicit declaration of function 'do_clone'
userns/simple_deep.c:45: warning: unused variable 'ret'
userns/simple_deep.c: In function 'do_clone':
userns/simple_deep.c:61: warning: implicit declaration of function 'getpagesize'
userns/simple_deep.c: In function 'main':
userns/simple_deep.c:92: warning: implicit declaration of function 'close'

Include unistd.h; forward-declare do_clone; remove unused variable.

Signed-off-by: Nathan Lynch <ntl@pobox.com>