cr_tests/pthread3: fix -Wall warnings
pthread3.c:38: warning: return type defaults to 'int'
pthread3.c: In function 'set_thread_info':
pthread3.c:41: warning: unused variable 'sp2'
pthread3.c:55: warning: control reaches end of non-void function
pthread3.c: At top level:
pthread3.c:58: warning: return type defaults to 'int'
pthread3.c: In function 'get_thread_info':
pthread3.c:62: warning: implicit declaration of function 'pthread_getconcurrency'
pthread3.c:86: warning: control reaches end of non-void function
pthread3.c: At top level:
pthread3.c:90: warning: return type defaults to 'int'
pthread3.c: In function 'compare_thread_info':
pthread3.c:138: warning: control reaches end of non-void function
pthread3.c: In function 'wait_for_threads':
pthread3.c:267: warning: unused variable 'status'
pthread3.c: At top level:
pthread3.c:291: warning: return type defaults to 'int'
pthread3.c: In function 'main':
pthread3.c:295: warning: unused variable 'status'
pthread3.c:376: warning: control reaches end of non-void function

Make function return types explicit; define __USE_UNIX98 for
pthread_getconcurrency; remove unused variables; add a return
statement for main().

Furthermore, with -m64:

pthread3.c: In function 'get_thread_info':
pthread3.c:65: warning: cast to pointer from integer of different size
pthread3.c:67: warning: cast to pointer from integer of different size
pthread3.c: In function 'compare_thread_info':
pthread3.c:97: warning: cast to pointer from integer of different size
pthread3.c:98: warning: cast to pointer from integer of different size
pthread3.c: In function 'do_work':
pthread3.c:143: warning: cast from pointer to integer of different size
pthread3.c: In function 'create_threads':
pthread3.c:247: warning: cast to pointer from integer of different size

Change struct thread_info->tid to long, which is the same size as
(void *).

Signed-off-by: Nathan Lynch <ntl@pobox.com>