cr_tests/pthread2: fix -Wall warnings
pthread2.c:50: warning: return type defaults to 'int'
pthread2.c: In function 'dump_attr':
pthread2.c:51: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:55: warning: return type defaults to 'int'
pthread2.c: In function 'get_affinity':
pthread2.c:60: warning: implicit declaration of function 'pthread_attr_getaffinity_np'
pthread2.c:67: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:70: warning: return type defaults to 'int'
pthread2.c: In function 'compare_affinity':
pthread2.c:80: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:83: warning: return type defaults to 'int'
pthread2.c: In function 'get_detachstate':
pthread2.c:92: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:96: warning: return type defaults to 'int'
pthread2.c: In function 'compare_detachstate':
pthread2.c:108: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:111: warning: return type defaults to 'int'
pthread2.c: In function 'get_guardsize':
pthread2.c:114: warning: pointer targets in passing argument 2 of 'pthread_attr_getguardsize' differ in signedness
pthread2.c:120: warning: control reaches end of non-void function
pthread2.c: In function 'compare_guardsize':
pthread2.c:127: warning: pointer targets in passing argument 3 of 'get_guardsize' differ in signedness
pthread2.c:128: warning: pointer targets in passing argument 3 of 'get_guardsize' differ in signedness
pthread2.c: At top level:
pthread2.c:138: warning: return type defaults to 'int'
pthread2.c: In function 'get_inheritsched':
pthread2.c:147: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:165: warning: return type defaults to 'int'
pthread2.c: In function 'get_schedparam':
pthread2.c:176: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:179: warning: return type defaults to 'int'
pthread2.c: In function 'compare_schedparam':
pthread2.c:190: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:193: warning: return type defaults to 'int'
pthread2.c: In function 'get_schedpolicy':
pthread2.c:202: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:206: warning: return type defaults to 'int'
pthread2.c: In function 'compare_schedpolicy':
pthread2.c:217: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:220: warning: return type defaults to 'int'
pthread2.c: In function 'get_scope':
pthread2.c:229: warning: control reaches end of non-void function
pthread2.c: At top level:
pthread2.c:232: warning: return type defaults to 'int'
pthread2.c: In function 'compare_scope':
pthread2.c:243: warning: control reaches end of non-void function
pthread2.c: In function 'get_stack':
pthread2.c:249: warning: pointer targets in passing argument 3 of 'pthread_attr_getstack' differ in signedness
pthread2.c: At top level:
pthread2.c:277: warning: return type defaults to 'int'
pthread2.c: In function 'compare_attr':
pthread2.c:302: warning: control reaches end of non-void function
pthread2.c: In function 'do_work':
pthread2.c:320: warning: implicit declaration of function 'pthread_getattr_np'
pthread2.c:333: warning: format '%d' expects type 'int', but argument 3 has type 'long int'
pthread2.c:359: warning: format '%d' expects type 'int', but argument 3 has type 'long int'
pthread2.c: In function 'create_threads':
pthread2.c:425: warning: format '%d' expects type 'int', but argument 3 has type 'long int'
pthread2.c: In function 'wait_for_threads':
pthread2.c:442: warning: unused variable 'status'
pthread2.c: At top level:
pthread2.c:467: warning: return type defaults to 'int'
pthread2.c: In function 'main':
pthread2.c:471: warning: unused variable 'status'
pthread2.c:550: warning: control reaches end of non-void function

The compare_* and get_* functions can be void; make it so.

Fix int vs. size_t confusion ("pointer targets differ in signedness").

Add #define _GNU_SOURCE for pthread_attr_getaffinity_np.

Fix printf formats for long vs int (%d -> %ld).

Remove unused variables.

Signed-off-by: Nathan Lynch <ntl@pobox.com>